### ISSUE TITLE
fragmented graph results only under certain conditions??

### ISSUE THREAD

**Issue by maureenbug** [spacegraphcats/spacegraphcats#417]
hi! I'm getting very different graph results (for the same sequence) depending on how I run it...
(I installed sgc within the past month from github, so I'm using a recent release)

1) it's run alone aka the only "search" sequence is a specific 1kb region of a particular contig
example .ymal file:

`catlas_base: my_contig`
`input_sequences:`
`- input_sequence.fasta.abundtrim`
`keep_graph_pendants: true`
`ksize: 31`
`radius: 1`
`search:`
`- search_1-1000bp_positions.fna`
`paired_reads: false`

then the graph will look great"
![my_contig_1-1000bp_positions_example1](https://user-images.githubusercontent.com/22039806/121226139-12de8580-c83f-11eb-86ed-6bfeb185319e.png)

2) it's run with all the other 1kb regions of the specific contig
example .ymal file:

`catlas_base: my_contig`
`input_sequences:`
`- input_sequence.fasta.abundtrim`
`keep_graph_pendants: true`
`ksize: 31`
`radius: 1`
`search:`
`- search_1-1000bp_positions.fna`
`- search_10001-11000bp_positions.fna`
`- search_1001-2000bp_positions.fna`
`- search_10501-11500bp_positions.fna`
`- search_11001-12000bp_positions.fna`
`- search_11501-12500bp_positions.fna`
`paired_reads: false`

then the graph I get (for my 1-1000bp position region of interest) is highly fragmented:
![my_contig_1-1000bp_positions_example2](https://user-images.githubusercontent.com/22039806/121226401-5e912f00-c83f-11eb-9322-2744e6deacbe.png)

any idea why this is happening? I initially was running all the individual 1kb regions together (like in example 2) because it runs much faster than running them all individually in example 1, but I keep getting these weird results.

thanks!

**Comment by ctb** [comment]
eek that's not good. I will dig into it shortly. Thank you!

**Comment by ctb** [comment]
(is it possible to share the underlying data with us? there's definitely no good reason for this to be happening!)

**Comment by maureenbug** [comment]
yeah let me get the files together and I'll email you the link for download!

**Comment by maureenbug** [comment]
okay just sent you the email

**Comment by ctb** [comment]
got it, thank you! might take me a few days

**Comment by maureenbug** [comment]
thank you!

**Comment by ctb** [comment]
hi @maureenbug thanks again for reporting this - I tried what I think is the same setup you have, but couldn't replicate. I will continue to poke at this, but I wanted to run my setup past you to make sure I got it right!

## sgc troubleshooting

file `maubug.yaml` sets up the catlas with five searches:
```yaml=
catlas_base: maubug
input_sequences:
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid.fasta.abundtrim
search:
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid_1-1000_no.fna
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid_1001-2000_no.fna
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid_1501-2500_no.fna
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid_2001-3000_no.fna
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid_2501-3500_no.fna
```
and puts results in the default output directory, `maubug_k31_r1_search_oh0`.

---

file `maubug2.yaml` just does a single search, and puts them in a different directory, `maubug_k31_r1_search_oh0_singleton`, using the `experiment` config parameter.
```yaml=
catlas_base: maubug
experiment: singleton
input_sequences:
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid.fasta.abundtrim
search:
- maureen/all_1kb_regions/contig_10007-cat_2_earlymid_1-1000_no.fna
```

---

When I compare the results they are indeed different. WTF...

```shell=
for i in contig*;
do
   diff $i ../maubug_k31_r1_search_oh0/$i
done
```
yields:
```
Binary files contig_10007-cat_2_earlymid_1-1000_no.fna.cdbg_ids.txt.gz and ../maubug_k31_r1_search_oh0/contig_10007-cat_2_earlymid_1-1000_no.fna.cdbg_ids.txt.gz differ
Binary files contig_10007-cat_2_earlymid_1-1000_no.fna.frontier.txt.gz and ../maubug_k31_r1_search_oh0/contig_10007-cat_2_earlymid_1-1000_no.fna.frontier.txt.gz differ
```

---

...but, when I uncompress and sort the cdbg_ids files, they are the same.

---

Next, when I run `extract_reads` and compare them, they are also the same.
